/**
 * Flogination V5 — Electron Main Process
 *
 * Entry point for the portable desktop application.
 * Spawns two child processes:
 *  1. Express API server (port 3001) — handles all business logic and DB access
 *  2. Next.js standalone server (port 3000) — serves the dashboard UI
 *
 * Data storage:
 *  - Portable mode: flogination.db and user-data/ are stored next to the .exe
 *    (PORTABLE_EXECUTABLE_DIR env var set by electron-builder portable target).
 *  - Dev mode: stored in the project root (process.cwd()).
 */

import { app, BrowserWindow, ipcMain, shell } from 'electron';
import path from 'path';
import { spawn, ChildProcess } from 'child_process';
import fs from 'fs';
import { autoUpdater } from 'electron-updater';

// ─────────────────────────────────────────────
// CONSTANTS
// ─────────────────────────────────────────────

const API_PORT = 3001;
const UI_PORT = 3000;
const API_HEALTH_POLL_INTERVAL_MS = 500;
const API_HEALTH_MAX_WAIT_MS = 30_000;
const DEFAULT_WINDOW_WIDTH = 1400;
const DEFAULT_WINDOW_HEIGHT = 900;
const MIN_WINDOW_WIDTH = 1200;
const MIN_WINDOW_HEIGHT = 700;

// ─────────────────────────────────────────────
// DATA DIRECTORY
// ─────────────────────────────────────────────

/**
 * Resolves the portable data directory.
 *
 * Priority:
 *  1. PORTABLE_EXECUTABLE_DIR — set by electron-builder when running as portable .exe
 *  2. Directory of the .exe in packaged mode
 *  3. process.cwd() in development
 */
function resolveDataDir(): string {
  if (process.env.PORTABLE_EXECUTABLE_DIR) {
    return process.env.PORTABLE_EXECUTABLE_DIR;
  }
  if (app.isPackaged) {
    return path.dirname(process.execPath);
  }
  return process.cwd();
}

const DATA_DIR = resolveDataDir();

// ─────────────────────────────────────────────
// STATE
// ─────────────────────────────────────────────

let mainWindow: BrowserWindow | null = null;
let apiProcess: ChildProcess | null = null;
let uiProcess: ChildProcess | null = null;

// ─────────────────────────────────────────────
// CHILD PROCESS HELPERS
// ─────────────────────────────────────────────

/**
 * Starts the Express API server as a child process.
 *
 * In production: runs the compiled `dist/server/index.js` with node.
 * In development: runs `src/server/index.ts` with tsx.
 *
 * Sets DB_PATH and USER_DATA_DIR so the server stores data next to the .exe.
 *
 * @example
 * startApiServer(); // spawns node or tsx with correct env vars
 */
function startApiServer(): void {
  const serverEnv: NodeJS.ProcessEnv = {
    ...process.env,
    PORT: String(API_PORT),
    NODE_ENV: app.isPackaged ? 'production' : 'development',
    DB_PATH: path.join(DATA_DIR, 'flogination.db'),
    USER_DATA_DIR: path.join(DATA_DIR, 'user-data'),
  };

  if (app.isPackaged) {
    const serverEntry = path.join(process.resourcesPath, 'dist', 'server', 'index.js');
    apiProcess = spawn('node', [serverEntry], {
      env: serverEnv,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } else {
    const serverEntry = path.join(__dirname, '..', 'src', 'server', 'index.ts');
    apiProcess = spawn('npx', ['tsx', serverEntry], {
      env: serverEnv,
      stdio: ['ignore', 'pipe', 'pipe'],
      shell: true,
    });
  }

  apiProcess.stdout?.on('data', (chunk: Buffer) => {
    console.log('[api]', chunk.toString().trimEnd());
  });
  apiProcess.stderr?.on('data', (chunk: Buffer) => {
    console.error('[api:err]', chunk.toString().trimEnd());
  });
  apiProcess.on('exit', (code) => {
    console.log(`[api] exited with code ${code}`);
  });
}

/**
 * Starts the Next.js standalone server as a child process.
 *
 * In production: runs `.next/standalone/server.js` (generated by `output: 'standalone'`).
 * In development: Next.js is already running via `npm run dev:client`, so this is a no-op.
 *
 * @example
 * startUiServer(); // spawns node server.js or skips in dev
 */
function startUiServer(): void {
  if (!app.isPackaged) {
    // In dev, Next.js is started separately via `npm run dev:client`
    return;
  }

  const standaloneServer = path.join(
    process.resourcesPath,
    'Flogination',
    'flogination-web',
    '.next',
    'standalone',
    'server.js'
  );

  const uiEnv: NodeJS.ProcessEnv = {
    ...process.env,
    PORT: String(UI_PORT),
    NODE_ENV: 'production',
    // Tell Next.js standalone where to find static assets
    NEXT_PUBLIC_API_URL: `http://localhost:${API_PORT}`,
  };

  uiProcess = spawn('node', [standaloneServer], {
    env: uiEnv,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  uiProcess.stdout?.on('data', (chunk: Buffer) => {
    console.log('[ui]', chunk.toString().trimEnd());
  });
  uiProcess.stderr?.on('data', (chunk: Buffer) => {
    console.error('[ui:err]', chunk.toString().trimEnd());
  });
  uiProcess.on('exit', (code) => {
    console.log(`[ui] exited with code ${code}`);
  });
}

/**
 * Kills a child process gracefully, falling back to SIGKILL after 3 seconds.
 *
 * @param proc - The child process to terminate
 * @param label - Label for log output
 */
function killProcess(proc: ChildProcess, label: string): void {
  if (proc.killed || proc.exitCode !== null) return;
  console.log(`[electron] killing ${label} process`);
  proc.kill('SIGTERM');
  const forceKill = setTimeout(() => {
    if (!proc.killed) proc.kill('SIGKILL');
  }, 3_000);
  proc.once('exit', () => clearTimeout(forceKill));
}

// ─────────────────────────────────────────────
// HEALTH POLLING
// ─────────────────────────────────────────────

/**
 * Polls the API health endpoint until it responds 200 or the timeout is reached.
 *
 * @returns Resolves when the API is ready; rejects on timeout.
 *
 * @example
 * await waitForApi(); // throws if server doesn't start within 30s
 */
async function waitForApi(): Promise<void> {
  const deadline = Date.now() + API_HEALTH_MAX_WAIT_MS;
  const url = `http://localhost:${API_PORT}/api/health`;

  while (Date.now() < deadline) {
    try {
      const res = await fetch(url);
      if (res.ok) return;
    } catch {
      // Server not up yet — keep polling
    }
    await new Promise<void>((resolve) => setTimeout(resolve, API_HEALTH_POLL_INTERVAL_MS));
  }

  throw new Error(`API server did not respond within ${API_HEALTH_MAX_WAIT_MS / 1_000}s`);
}

// ─────────────────────────────────────────────
// BROWSER WINDOW
// ─────────────────────────────────────────────

/**
 * Creates and configures the main application BrowserWindow.
 * The window is shown only after the renderer signals `ready-to-show`
 * to avoid a white flash on startup.
 *
 * @example
 * createWindow(); // opens the dashboard at http://localhost:3000
 */
function createWindow(): void {
  mainWindow = new BrowserWindow({
    width: DEFAULT_WINDOW_WIDTH,
    height: DEFAULT_WINDOW_HEIGHT,
    minWidth: MIN_WINDOW_WIDTH,
    minHeight: MIN_WINDOW_HEIGHT,
    title: 'Flogination',
    backgroundColor: '#0c0e11',
    show: false, // shown after ready-to-show to avoid white flash
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
  });

  // Route external links to the system browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('http')) {
      shell.openExternal(url);
      return { action: 'deny' };
    }
    return { action: 'allow' };
  });

  mainWindow.loadURL(`http://localhost:${UI_PORT}`);

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ─────────────────────────────────────────────
// IPC HANDLERS
// ─────────────────────────────────────────────

/**
 * Registers IPC handlers exposed to the renderer via the preload bridge.
 *
 * Channels:
 *  - `get-version` → returns the app version string from package.json
 *  - `open-external` → opens a URL in the system browser
 *  - `check-for-updates` → manually trigger update check
 *
 * @example
 * registerIpcHandlers(); // call once before creating the window
 */
function registerIpcHandlers(): void {
  ipcMain.handle('get-version', () => app.getVersion());

  ipcMain.handle('open-external', (_event, url: string) => {
    // Only allow http/https URLs to prevent arbitrary protocol execution
    if (typeof url === 'string' && (url.startsWith('https://') || url.startsWith('http://'))) {
      return shell.openExternal(url);
    }
  });

  ipcMain.handle('check-for-updates', () => {
    if (app.isPackaged) {
      autoUpdater.checkForUpdates();
    }
  });
}

// ─────────────────────────────────────────────
// VERSION GATE (GitHub Gist)
// ─────────────────────────────────────────────

/**
 * Checks a public GitHub Gist for version gate config.
 * If the current version is below minVersion or allowed=false,
 * returns a message to show the user and optionally blocks startup.
 *
 * Gist URL: https://gist.githubusercontent.com/neloy559/[GIST_ID]/raw/flogination-version.json
 * Gist format: { "minVersion": "0.1.0", "allowed": true, "message": "", "demoExpired": false }
 *
 * Fails open — if the Gist is unreachable, the app starts normally.
 */
const GIST_URL = 'https://gist.githubusercontent.com/neloy559/db0cf2a709a2f60807fcd0b46da007df/raw/flogination-version.json';

interface VersionGateConfig {
  minVersion: string;
  allowed: boolean;
  message: string;
  demoExpired: boolean;
}

function compareVersions(a: string, b: string): number {
  const pa = a.split('.').map(Number);
  const pb = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    if ((pa[i] ?? 0) > (pb[i] ?? 0)) return 1;
    if ((pa[i] ?? 0) < (pb[i] ?? 0)) return -1;
  }
  return 0;
}

async function checkVersionGate(): Promise<{ blocked: boolean; message: string }> {
  try {
    const res = await fetch(GIST_URL, { signal: AbortSignal.timeout(5_000) });
    if (!res.ok) return { blocked: false, message: '' };

    const config = await res.json() as VersionGateConfig;
    const currentVersion = app.getVersion();

    if (!config.allowed) {
      return { blocked: true, message: config.message || 'This version has been disabled. Please download the latest version.' };
    }

    if (config.demoExpired) {
      return { blocked: true, message: config.message || 'The demo period has ended. Please upgrade to the full version.' };
    }

    if (config.minVersion && compareVersions(currentVersion, config.minVersion) < 0) {
      return {
        blocked: true,
        message: config.message || `Version ${currentVersion} is no longer supported. Please update to v${config.minVersion} or later.`,
      };
    }

    return { blocked: false, message: '' };
  } catch {
    // Gist unreachable — fail open, app starts normally
    return { blocked: false, message: '' };
  }
}

// ─────────────────────────────────────────────
// AUTO-UPDATER SETUP
// ─────────────────────────────────────────────

/**
 * Configures electron-updater to check GitHub Releases for new versions.
 * Shows a notification in the renderer when an update is available.
 * Downloads silently and installs on next restart.
 */
function setupAutoUpdater(): void {
  if (!app.isPackaged) return;

  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;

  autoUpdater.on('update-available', (info) => {
    mainWindow?.webContents.send('update-available', {
      version: info.version,
      releaseNotes: info.releaseNotes,
    });
  });

  autoUpdater.on('update-downloaded', () => {
    mainWindow?.webContents.send('update-downloaded');
  });

  autoUpdater.on('error', (err) => {
    console.error('[updater] error:', err.message);
  });

  // Check 3 seconds after startup to avoid blocking app launch
  setTimeout(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('[updater] check failed:', err.message);
    });
  }, 3_000);
}

// ─────────────────────────────────────────────
// APP LIFECYCLE
// ─────────────────────────────────────────────

app.whenReady().then(async () => {
  // Ensure portable data directories exist before the server starts
  fs.mkdirSync(path.join(DATA_DIR, 'user-data'), { recursive: true });

  registerIpcHandlers();
  setupAutoUpdater();
  startApiServer();
  startUiServer();

  try {
    await waitForApi();
    console.log('[electron] API server ready');
  } catch (err) {
    console.error('[electron] API server failed to start:', err);
    // Continue anyway — the window will show an error page
  }

  createWindow();

  // Check version gate after window is created so we can show a message if blocked
  const gate = await checkVersionGate();
  if (gate.blocked) {
    mainWindow?.webContents.once('did-finish-load', () => {
      mainWindow?.webContents.send('version-blocked', { message: gate.message });
    });
  }

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('before-quit', () => {
  if (apiProcess) killProcess(apiProcess, 'api');
  if (uiProcess) killProcess(uiProcess, 'ui');
});
